service: import-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  environment:
    CATALOG_SQS_URL: '${cf:product-service-dev.SQSQueueUrl}'
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 's3:ListBucket'
      Resource:
        - 'arn:aws:s3:::aws-nodejs-app-uploaded'
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::aws-nodejs-app-uploaded/*'
    - Effect: 'Allow'
      Action: 'sqs:*'
      Resource:
        - '${cf:product-service-dev.SQSQueueArn}'

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: aws-nodejs-app-uploaded
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true